'use strict';
const TANISHA_ADMIN_BUILD='V24-SUPABASE-SYNC';
let currentProducts=[],currentSettingsId=null,currentOffers=[],currentReviews=[],currentVideos=[];
const $=id=>document.getElementById(id),html=(v='')=>String(v).replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const showLogin=()=>{$('login').classList.remove('hidden');$('dash').classList.add('hidden')};
const showDash=()=>{$('login').classList.add('hidden');$('dash').classList.remove('hidden');init()};
supabaseClient.auth.getSession().then(({data})=>data.session?showDash():showLogin());
$('showPassword').onclick=()=>{const p=$('password');p.type=p.type==='password'?'text':'password';$('showPassword').textContent=p.type==='password'?'Show':'Hide'};
$('loginBtn').onclick=async()=>{$('loginStatus').textContent='Logging in…';const {error}=await supabaseClient.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error){$('loginStatus').textContent=error.message;return}$('loginStatus').textContent='';showDash()};
$('logout').onclick=async()=>{await supabaseClient.auth.signOut();location.reload()};
async function init(){
  console.info('Tanisha Admin',TANISHA_ADMIN_BUILD);
  await Promise.allSettled([renderRows(),loadSettings(),loadOffers(),loadReviews(),loadVideos()]);
  const requested=new URLSearchParams(location.search).get('tab');
  if(requested)openAdminTab(requested,document.querySelector(`[data-tab=\"${requested}\"]`));
}
async function renderRows(){const {data,error}=await supabaseClient.from('products').select('*').order('created_at',{ascending:false});if(error){$('adminStatus').textContent=error.message;return}currentProducts=data||[];filterAdminRows();$('statProducts').textContent=currentProducts.length;$('statStock').textContent=currentProducts.reduce((s,p)=>s+Number(p.stock||0),0);$('statFeatured').textContent=currentProducts.filter(p=>p.featured).length}
function filterAdminRows(){const q=$('adminSearch').value.trim().toLowerCase(),list=currentProducts.filter(p=>`${p.name||''} ${p.category||''} ${p.design_number||''}`.toLowerCase().includes(q));$('productCount').textContent=`${list.length} products`;$('rows').innerHTML=list.map(p=>`<div class="row"><img src="${html(p.image_url||'product-placeholder.svg')}" onerror="this.src='product-placeholder.svg'"><div><b>${html(p.name)}</b><br><small>${html(p.category||'')} ${p.design_number?`• D.No ${html(p.design_number)}`:''}</small></div><div>₹${Number(p.price||0).toLocaleString('en-IN')}</div><div><span class="pill ${Number(p.stock)>0?'ok':'low'}">Stock ${Number(p.stock||0)}</span></div><div class="actions"><button data-edit="${p.id}">Edit</button><button class="delete" data-delete="${p.id}">Delete</button></div></div>`).join('')||'<p class="empty">No products found.</p>'}
$('adminSearch').oninput=filterAdminRows;$('add').onclick=()=>openForm();$('close').onclick=()=>$('productModal').classList.add('hidden');
function openForm(p){$('productForm').reset();$('uploadStatus').textContent='';$('productForm').elements.active.checked=true;if(p)Object.keys(p).forEach(k=>{const e=$('productForm').elements[k];if(e)e.type==='checkbox'?e.checked=!!p[k]:e.value=p[k]??''});$('productModal').classList.remove('hidden')}
document.addEventListener('click',async e=>{const t=e.target.closest('[data-edit],[data-delete],[data-tab],[data-offer-edit],[data-offer-delete],[data-review-approve],[data-review-delete],[data-video-edit],[data-video-delete]');if(!t)return;if(t.dataset.edit)openForm(currentProducts.find(p=>String(p.id)===t.dataset.edit));if(t.dataset.delete&&confirm('Delete product?')){const {error}=await supabaseClient.from('products').delete().eq('id',t.dataset.delete);error?alert(error.message):renderRows()}if(t.dataset.tab){openAdminTab(t.dataset.tab,t)}if(t.dataset.offerEdit)fillOffer(currentOffers.find(o=>String(o.id)===t.dataset.offerEdit));if(t.dataset.offerDelete&&confirm('Delete offer?')){const {error}=await supabaseClient.from('offers').delete().eq('id',t.dataset.offerDelete);error?alert(error.message):loadOffers()}if(t.dataset.reviewApprove){const {error}=await supabaseClient.from('reviews').update({approved:true}).eq('id',t.dataset.reviewApprove);error?alert(error.message):loadReviews()}if(t.dataset.reviewDelete&&confirm('Delete review?')){const {error}=await supabaseClient.from('reviews').delete().eq('id',t.dataset.reviewDelete);error?alert(error.message):loadReviews()}if(t.dataset.videoEdit)fillVideo(currentVideos.find(v=>String(v.id)===t.dataset.videoEdit));if(t.dataset.videoDelete&&confirm('Delete video?')){const v=currentVideos.find(x=>String(x.id)===t.dataset.videoDelete);const {error}=await supabaseClient.from('videos').delete().eq('id',t.dataset.videoDelete);if(!error&&v?.storage_path)await supabaseClient.storage.from('store-videos').remove([v.storage_path]);error?alert(error.message):loadVideos()}});

function openAdminTab(name,button){
  const valid=['products','settings','videos','reviews'];
  if(!valid.includes(name))return;
  document.querySelectorAll('nav [data-tab]').forEach(b=>b.classList.toggle('active',b===button||b.dataset.tab===name));
  valid.forEach(x=>{const panel=$(x+'Tab');if(panel)panel.classList.toggle('hidden',x!==name)});
  if(name==='videos'){
    const panel=$('videosTab');
    if(panel){panel.style.display='block';panel.style.visibility='visible';panel.style.opacity='1'}
    loadVideos().catch(err=>{const st=$('videoAdminStatus');if(st)st.textContent='Video Manager error: '+err.message});
  }
  window.scrollTo({top:document.querySelector('nav')?.offsetTop||0,behavior:'smooth'});
}

$('productForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;btn.textContent='Saving…';const f=Object.fromEntries(new FormData(e.target)),files=[...$('imageFiles').files],urls=[];$('uploadStatus').textContent=files.length?`Uploading ${files.length} image(s)…`:'';for(const file of files){if(file.size>8*1024*1024){btn.disabled=false;btn.textContent='Save Product';return alert(`${file.name} is larger than 8 MB`)}const safe=file.name.replace(/[^a-zA-Z0-9.]/g,'-'),path=`products/${Date.now()}-${crypto.randomUUID()}-${safe}`;const up=await supabaseClient.storage.from('product-images').upload(path,file,{cacheControl:'3600',upsert:false});if(up.error){btn.disabled=false;btn.textContent='Save Product';return alert(up.error.message)}urls.push(supabaseClient.storage.from('product-images').getPublicUrl(path).data.publicUrl)}const existing=currentProducts.find(p=>String(p.id)===String(f.id));let old=[];if(Array.isArray(existing?.image_urls))old=existing.image_urls;else if(existing?.image_urls){try{old=JSON.parse(existing.image_urls)}catch{}}const all=[...old,...urls];const main=f.image_url||all[0]||null;const payload={name:f.name.trim(),design_number:f.design_number?.trim()||null,category:f.category.trim(),description:f.description?.trim()||null,fabric:f.fabric?.trim()||null,work:f.work?.trim()||null,wash_care:f.wash_care?.trim()||null,price:Number(f.price||0),original_price:f.original_price?Number(f.original_price):null,image_url:main,image_urls:all,sizes:f.sizes?.trim()||null,colors:f.colors?.trim()||null,stock:Number(f.stock||0),featured:e.target.elements.featured.checked,active:e.target.elements.active.checked};const r=f.id?await supabaseClient.from('products').update(payload).eq('id',f.id):await supabaseClient.from('products').insert(payload);btn.disabled=false;btn.textContent='Save Product';if(r.error)return alert(r.error.message);$('productModal').classList.add('hidden');await renderRows();alert('Product saved successfully')};
async function loadSettings(){const {data,error}=await supabaseClient.from('site_settings').select('*').order('id').limit(1).maybeSingle();if(error)return alert(error.message);if(!data)return;currentSettingsId=data.id;Object.keys(data).forEach(k=>{if($('settingsForm').elements[k])$('settingsForm').elements[k].value=data[k]??''})}
$('settingsForm').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.target));const r=currentSettingsId?await supabaseClient.from('site_settings').update(p).eq('id',currentSettingsId):await supabaseClient.from('site_settings').insert(p).select().single();if(r.error)return alert(r.error.message);if(r.data)currentSettingsId=r.data.id;alert('Settings saved')};
async function loadOffers(){const {data,error}=await supabaseClient.from('offers').select('*').order('created_at',{ascending:false});if(error)return alert(error.message);currentOffers=data||[];$('offerRows').innerHTML=currentOffers.map(o=>`<div class="row offerRow"><div></div><div><b>${html(o.title)}</b><br><small>${o.active?'Active':'Inactive'} ${o.start_date?`• ${o.start_date}`:''}</small></div><div>${html(o.discount_text||'')}</div><div></div><div class="actions"><button data-offer-edit="${o.id}">Edit</button><button class="delete" data-offer-delete="${o.id}">Delete</button></div></div>`).join('')||'<p class="empty">No offers yet.</p>'}
function fillOffer(o){$('offerForm').reset();Object.keys(o||{}).forEach(k=>{const e=$('offerForm').elements[k];if(e)e.type==='checkbox'?e.checked=!!o[k]:e.value=o[k]??''})}
$('newOffer').onclick=()=>{$('offerForm').reset();$('offerForm').elements.active.checked=true};
$('offerForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),p={title:f.title||'Special Offer',subtitle:f.subtitle||null,discount_text:f.discount_text||null,banner_image:f.banner_image||null,start_date:f.start_date||null,end_date:f.end_date||null,active:e.target.elements.active.checked};const r=f.id?await supabaseClient.from('offers').update(p).eq('id',f.id):await supabaseClient.from('offers').insert(p);if(r.error)return alert(r.error.message);e.target.reset();await loadOffers();alert('Offer saved')};
async function loadReviews(){const {data,error}=await supabaseClient.from('reviews').select('*').order('created_at',{ascending:false});if(error){$('reviewRows').innerHTML=error.message;return}currentReviews=data||[];$('pendingCount').textContent=`${currentReviews.filter(r=>!r.approved).length} pending`;if($('statReviews'))$('statReviews').textContent=currentReviews.filter(r=>!r.approved).length;$('reviewRows').innerHTML=currentReviews.map(r=>`<div class="reviewRow"><div><b>${html(r.customer_name)}</b> — <span class="stars">${'★'.repeat(r.rating)}</span><br><p>${html(r.review_text)}</p><small>${r.approved?'Approved':'Pending'}</small></div><div class="actions">${r.approved?'':`<button data-review-approve="${r.id}">Approve</button>`}<button class="delete" data-review-delete="${r.id}">Delete</button></div></div>`).join('')||'<p class="empty">No reviews yet.</p>'}


async function loadVideos(){
  const panel=$('videosTab'), rows=$('videoRows'), form=$('videoForm'), status=$('videoAdminStatus');
  if(panel){panel.style.visibility='visible';panel.style.opacity='1'}
  if(form)form.style.display='grid';
  if(status)status.textContent='Loading videos…';
  const {data,error}=await supabaseClient.from('videos').select('*').order('created_at',{ascending:false});
  if(error){if(status)status.textContent=`Videos setup missing: ${error.message}. V22 setup.sql run karein.`;return}
  currentVideos=data||[]; if(status)status.textContent=`${currentVideos.length} video(s)`;
  if(!rows)return;
  rows.innerHTML=currentVideos.map(v=>`<div class="videoAdminRow"><video src="${html(v.video_url)}" muted playsinline preload="metadata"></video><div><b>${html(v.title)}</b><p>${html(v.category||'')} ${v.active?'• Visible':'• Hidden'}</p><small>${html(v.caption||'')}</small></div><div class="actions"><button data-video-edit="${v.id}">Edit</button><button class="delete" data-video-delete="${v.id}">Delete</button></div></div>`).join('')||'<p class="empty">No videos yet. + Add Video dabayein.</p>';
}
function fillVideo(v){const f=$('videoForm');f.reset();f.elements.active.checked=true;Object.keys(v||{}).forEach(k=>{const e=f.elements[k];if(e)e.type==='checkbox'?e.checked=!!v[k]:e.value=v[k]??''});f.scrollIntoView({behavior:'smooth',block:'start'})}
if($('newVideo'))$('newVideo').onclick=()=>{fillVideo(null);$('videoForm').classList.remove('hidden')};
$('videoForm').onsubmit=async e=>{
  e.preventDefault();const btn=e.submitter;btn.disabled=true;btn.textContent='Saving…';const f=Object.fromEntries(new FormData(e.target));const file=$('videoFile').files[0];let video_url=f.video_url||null,storage_path=f.storage_path||null;
  if(!f.id&&!file){btn.disabled=false;btn.textContent='Save Video';return alert('Please select an MP4/WebM video')}
  if(file){if(file.size>50*1024*1024){btn.disabled=false;btn.textContent='Save Video';return alert('Video maximum 50 MB honi chahiye')}if(!['video/mp4','video/webm'].includes(file.type)){btn.disabled=false;btn.textContent='Save Video';return alert('Sirf MP4 ya WebM upload karein')}const safe=file.name.replace(/[^a-zA-Z0-9.]/g,'-');storage_path=`videos/${Date.now()}-${crypto.randomUUID()}-${safe}`;$('videoUploadStatus').textContent='Uploading video…';const up=await supabaseClient.storage.from('store-videos').upload(storage_path,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(up.error){btn.disabled=false;btn.textContent='Save Video';return alert(up.error.message)}video_url=supabaseClient.storage.from('store-videos').getPublicUrl(storage_path).data.publicUrl}
  const payload={title:f.title.trim(),category:f.category?.trim()||null,caption:f.caption?.trim()||null,video_url,storage_path,active:e.target.elements.active.checked};const r=f.id?await supabaseClient.from('videos').update(payload).eq('id',f.id):await supabaseClient.from('videos').insert(payload);btn.disabled=false;btn.textContent='Save Video';$('videoUploadStatus').textContent='';if(r.error)return alert(r.error.message);e.target.reset();e.target.elements.active.checked=true;await loadVideos();alert('Video saved successfully')
};
