-- TANISHA ETHNICS PREMIUM V3.0
-- Supabase SQL Editor me ek baar poora Run karein.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  design_number text,
  category text,
  description text,
  price numeric not null default 0,
  original_price numeric,
  image_url text,
  image_urls jsonb not null default '[]'::jsonb,
  sizes text,
  colors text,
  stock integer not null default 0,
  featured boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.products add column if not exists image_urls jsonb default '[]'::jsonb;

create table if not exists public.offers (
  id bigint generated by default as identity primary key,
  title text not null default 'Special Offer',
  subtitle text,
  discount_text text,
  banner_image text,
  start_date date,
  end_date date,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.offers add column if not exists banner_image text;

create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  store_name text default 'Tanisha Ethnics',
  whatsapp_number text default '918141152565',
  instagram_url text default 'https://www.instagram.com/tanisha.ethnic/',
  announcement_text text default 'Welcome to Tanisha Ethnics'
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  customer_name text not null check (char_length(customer_name) between 1 and 60),
  rating integer not null check (rating between 1 and 5),
  review_text text not null check (char_length(review_text) between 2 and 600),
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

insert into public.site_settings (store_name,whatsapp_number,instagram_url,announcement_text)
select 'Tanisha Ethnics','918141152565','https://www.instagram.com/tanisha.ethnic/','Welcome to Tanisha Ethnics'
where not exists (select 1 from public.site_settings);

alter table public.products enable row level security;
alter table public.offers enable row level security;
alter table public.site_settings enable row level security;
alter table public.reviews enable row level security;

-- Public storefront read access
 drop policy if exists "Public read active products" on public.products;
create policy "Public read active products" on public.products for select to anon, authenticated using (active = true);
drop policy if exists "Public read active offers" on public.offers;
create policy "Public read active offers" on public.offers for select to anon, authenticated using (active = true);
drop policy if exists "Public read site settings" on public.site_settings;
create policy "Public read site settings" on public.site_settings for select to anon, authenticated using (true);

-- Authenticated admin access
 drop policy if exists "Authenticated manage products" on public.products;
create policy "Authenticated manage products" on public.products for all to authenticated using (true) with check (true);
drop policy if exists "Authenticated manage offers" on public.offers;
create policy "Authenticated manage offers" on public.offers for all to authenticated using (true) with check (true);
drop policy if exists "Authenticated manage settings" on public.site_settings;
create policy "Authenticated manage settings" on public.site_settings for all to authenticated using (true) with check (true);

-- Reviews
 drop policy if exists "Public read approved reviews" on public.reviews;
create policy "Public read approved reviews" on public.reviews for select to anon, authenticated using (approved = true);
drop policy if exists "Public submit reviews" on public.reviews;
create policy "Public submit reviews" on public.reviews for insert to anon, authenticated with check (approved = false);
drop policy if exists "Authenticated manage reviews" on public.reviews;
create policy "Authenticated manage reviews" on public.reviews for all to authenticated using (true) with check (true);

-- Storage
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('product-images','product-images',true,8388608,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set public=true,file_size_limit=8388608,allowed_mime_types=array['image/jpeg','image/png','image/webp','image/gif'];

drop policy if exists "Public view product images" on storage.objects;
create policy "Public view product images" on storage.objects for select to public using (bucket_id='product-images');
drop policy if exists "Authenticated upload product images" on storage.objects;
create policy "Authenticated upload product images" on storage.objects for insert to authenticated with check (bucket_id='product-images');
drop policy if exists "Authenticated update product images" on storage.objects;
create policy "Authenticated update product images" on storage.objects for update to authenticated using (bucket_id='product-images') with check (bucket_id='product-images');
drop policy if exists "Authenticated delete product images" on storage.objects;
create policy "Authenticated delete product images" on storage.objects for delete to authenticated using (bucket_id='product-images');


-- V14 ULTIMATE ADDITIONS
alter table public.products add column if not exists fabric text;
alter table public.products add column if not exists work text;
alter table public.products add column if not exists wash_care text;
alter table public.reviews add column if not exists photo_url text;
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types) values ('review-images','review-images',true,4194304,array['image/jpeg','image/png','image/webp']) on conflict (id) do update set public=true,file_size_limit=4194304;
drop policy if exists "Public view review images" on storage.objects;
create policy "Public view review images" on storage.objects for select to public using (bucket_id='review-images');
drop policy if exists "Public upload review images" on storage.objects;
create policy "Public upload review images" on storage.objects for insert to anon, authenticated with check (bucket_id='review-images');


-- V22 VIDEO MANAGER (run once; safe to re-run)
create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  title text not null,
  category text,
  caption text,
  video_url text not null,
  poster_url text,
  storage_path text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.videos enable row level security;
drop policy if exists "Public read active videos" on public.videos;
create policy "Public read active videos" on public.videos for select to anon, authenticated using (active=true);
drop policy if exists "Authenticated manage videos" on public.videos;
create policy "Authenticated manage videos" on public.videos for all to authenticated using (true) with check (true);
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('store-videos','store-videos',true,52428800,array['video/mp4','video/webm'])
on conflict (id) do update set public=true,file_size_limit=52428800,allowed_mime_types=array['video/mp4','video/webm'];
drop policy if exists "Public view store videos" on storage.objects;
create policy "Public view store videos" on storage.objects for select to public using (bucket_id='store-videos');
drop policy if exists "Authenticated upload store videos" on storage.objects;
create policy "Authenticated upload store videos" on storage.objects for insert to authenticated with check (bucket_id='store-videos');
drop policy if exists "Authenticated update store videos" on storage.objects;
create policy "Authenticated update store videos" on storage.objects for update to authenticated using (bucket_id='store-videos') with check (bucket_id='store-videos');
drop policy if exists "Authenticated delete store videos" on storage.objects;
create policy "Authenticated delete store videos" on storage.objects for delete to authenticated using (bucket_id='store-videos');
